# Import Library

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Data

In [63]:
df = pd.read_csv('raw-data/usco2015v2.0.csv')
df.head()

,"Version 2.0: Dieter, C.A., Linsey, K.S., Caldwell, R.R., Harris, M.A., Ivahnenko, T.I., Lovelace, J.K., Maupin, M.A., and Barber, N.L., 2018, Estimated use of water in the United States county-level data for 2015 (ver. 2.0, June 2018): U.S. Geological Survey data release, https://doi.org/10.5066/F7TB15V5.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140
0,STATE,STATEFIPS,COUNTY,COUNTYFIPS,FIPS,YEAR,TP-TotPop,PS-GWPop,PS-SWPop,PS-TOPop,...,TO-WGWTo,TO-WSWFr,TO-WSWSa,TO-WSWTo,TO-WFrTo,TO-WSaTo,TO-Wtotl,TO-CUsFrPartial,TO-CUsSaPartial,TO-CUTotPartial
1,AL,01,Autauga County,001,01001,2015,55.347,--,--,48.998,...,10.69,45.72,0.00,45.72,56.41,0.00,56.41,13.18,0.00,13.18
2,AL,01,Baldwin County,003,01003,2015,203.709,--,--,174.907,...,73.38,11.32,0.00,11.32,84.70,0.00,84.70,58.28,0.00,58.28
3,AL,01,Barbour County,005,01005,2015,26.489,--,--,24.587,...,6.06,2.96,0.00,2.96,9.02,0.00,9.02,2.96,0.00,2.96
4,AL,01,Bibb County,007,01007,2015,22.583,--,--,20.947,...,5.67,0.20,0.00,0.20,5.87,0.00,5.87,0.19,0.00,0.19

# Change column names

> Function used to change column names from "Unnamed: n" to their respective column name and to drop row 0

In [70]:
def preprocess_columns(df):

    # List of all columns
    data_list = ['STATE', 'STATEFIPS', 'COUNTY', 'COUNTYFIPS', 'FIPS', 'YEAR', 'TP-TotPop', 'PS-GWPop', 'PS-SWPop', 'PS-TOPop', 'PS-WGWFr', 'PS-WGWSa',
                 'PS-WGWTo', 'PS-WSWFr', 'PS-WSWSa', 'PS-WSWTo', 'PS-WFrTo', 'PS-WSaTo', 'PS-Wtotl', 'DO-SSPop', 'DO-WGWFr', 'DO-WSWFr', 'DO-WFrTo', 'DO-SSPCp',
                 'DO-PSDel', 'DO-PSPCp', 'DO-WDelv',  'IN-WGWFr', 'IN-WGWSa', 'IN-WGWTo', 'IN-WSWFr', 'IN-WSWSa', 'IN-WSWTo', 'IN-WFrTo', 'IN-WSaTo', 'IN-Wtotl',
                 'IR-WGWFr', 'IR-WSWFr', 'IR-WFrTo', 'IR-RecWW', 'IR-CUsFr', 'IR-IrSpr', 'IR-IrMic', 'IR-IrSur', 'IR-IrTot', 'IC-WGWFr', 'IC-WSWFr', 'IC-WFrTo',
                 'IC-RecWW', 'IC-CUsFr', 'IC-IrSpr', 'IC-IrMic', 'IC-IrSur', 'IC-IrTot', 'IG-WGWFr', 'IG-WSWFr', 'IG-WFrTo', 'IG-RecWW', 'IG-CUsFr', 'IG-IrSpr',
                 'IG-IrMic', 'IG-IrSur', 'IG-IrTot', 'LI-WGWFr', 'LI-WSWFr', 'LI-WFrTo', 'AQ-WGWFr', 'AQ-WGWSa', 'AQ-WGWTo', 'AQ-WSWFr', 'AQ-WSWSa', 'AQ-WSWTo',
                 'AQ-WFrTo', 'AQ-WSaTo', 'AQ-Wtotl', 'MI-WGWFr', 'MI-WGWSa', 'MI-WGWTo', 'MI-WSWFr', 'MI-WSWSa', 'MI-WSWTo', 'MI-WFrTo', 'MI-WSaTo', 'MI-Wtotl', 
                 'PT-WGWFr', 'PT-WGWSa', 'PT-WGWTo', 'PT-WSWFr', 'PT-WSWSa', 'PT-WSWTo', 'PT-WFrTo', 'PT-WSaTo', 'PT-Wtotl', 'PT-RecWW', 'PT-PSDel', 'PT-CUsFr',
                 'PT-CUsSa', 'PT-CUTot', 'PT-Power', 'PO-WGWFr', 'PO-WGWSa', 'PO-WGWTo', 'PO-WSWFr', 'PO-WSWSa', 'PO-WSWTo', 'PO-WFrTo', 'PO-WSaTo', 'PO-Wtotl',
                 'PO-RecWW', 'PO-PSDel', 'PO-CUsFr', 'PO-CUsSa', 'PO-CUTot', 'PO-Power', 'PC-WGWFr', 'PC-WGWSa', 'PC-WGWTo', 'PC-WSWFr', 'PC-WSWSa', 'PC-WSWTo',
                 'PC-WFrTo', 'PC-WSaTo', 'PC-Wtotl', 'PC-RecWW', 'PC-PSDel', 'PC-CUsFr', 'PC-CUsSa', 'PC-CUTot', 'PC-Power', 'TO-WGWFr', 'TO-WGWSa', 'TO-WGWTo',
                 'TO-WSWFr', 'TO-WSWSa', 'TO-WSWTo', 'TO-WFrTo', 'TO-WSaTo', 'TO-Wtotl', 'TO-CUsFrPartial', 'TO-CUsSaPartial', 'TO-CUTotPartial']
    
    print(len(data_list))
    
    # Change column names
    df.columns = data_list

    # Drop the first row
    df = df.drop(0)
    
    return df

In [73]:
df = preprocess_columns(df)
df.head()

141

,STATE,STATEFIPS,COUNTY,COUNTYFIPS,FIPS,YEAR,TP-TotPop,PS-GWPop,PS-SWPop,PS-TOPop,...,TO-WGWTo,TO-WSWFr,TO-WSWSa,TO-WSWTo,TO-WFrTo,TO-WSaTo,TO-Wtotl,TO-CUsFrPartial,TO-CUsSaPartial,TO-CUTotPartial
1,AL,01,Autauga County,001,01001,2015,55.347,--,--,48.998,...,10.69,45.72,0.00,45.72,56.41,0.00,56.41,13.18,0.00,13.18
2,AL,01,Baldwin County,003,01003,2015,203.709,--,--,174.907,...,73.38,11.32,0.00,11.32,84.70,0.00,84.70,58.28,0.00,58.28
3,AL,01,Barbour County,005,01005,2015,26.489,--,--,24.587,...,6.06,2.96,0.00,2.96,9.02,0.00,9.02,2.96,0.00,2.96
4,AL,01,Bibb County,007,01007,2015,22.583,--,--,20.947,...,5.67,0.20,0.00,0.20,5.87,0.00,5.87,0.19,0.00,0.19
5,AL,01,Blount County,009,01009,2015,57.673,--,--,44.815,...,4.64,55.43,0.00,55.43,60.07,0.00,60.07,1.08,0.00,1.08

# Condense Features

> Function to condense groups and drop unnecessary features

In [74]:
def group_and_drop_columns(df):
    # Group columns
    df['demographic_location_information'] = df[['STATE', 'COUNTY', 'FIPS']].values.tolist()
    df['population'] = df['TP-TotPop']
    df['water_supply'] = df[['PS-GWPop', 'PS-SWPop', 'PS-TOPop']].values.tolist()
    df['water_supply_withdrawals_by_source'] = df[['PS-WGWFr', 'PS-WGWSa', 'PS-WGWTo', 'PS-WSWFr', 'PS-WSWSa', 'PS-WSWTo', 'PS-WFrTo', 'PS-WSaTo', 'PS-Wtotl']].values.tolist()
    df['other_water_usage_categories'] = df[['DO-SSPop', 'DO-WGWFr', 'DO-WSWFr', 'DO-WFrTo', 'DO-SSPCp', 'DO-PSDel', 'DO-PSPCp', 'DO-WDelv']].values.tolist()
    df['industrial_water_usage'] = df[['IN-WGWFr', 'IN-WGWSa', 'IN-WGWTo', 'IN-WSWFr', 'IN-WSWSa', 'IN-WSWTo', 'IN-WFrTo', 'IN-WSaTo', 'IN-Wtotl']].values.tolist()
    df['irrigation_water_usage'] = df[['IR-WGWFr', 'IR-WSWFr', 'IR-WFrTo', 'IR-RecWW', 'IR-CUsFr', 'IR-IrSpr', 'IR-IrMic', 'IR-IrSur', 'IR-IrTot']].values.tolist()
    df['irrigation_crop_usage'] = df[['IC-WGWFr', 'IC-WSWFr', 'IC-WFrTo', 'IC-RecWW', 'IC-CUsFr', 'IC-IrSpr', 'IC-IrMic', 'IC-IrSur', 'IC-IrTot']].values.tolist()
    df['irrigation_golf_usage'] = df[['IG-WGWFr', 'IG-WSWFr', 'IG-WFrTo','IG-RecWW', 'IG-CUsFr', 'IG-IrSpr', 'IG-IrMic', 'IG-IrSur', 'IG-IrTot']].values.tolist()
    df['livestock_water_usage'] = df[['LI-WGWFr', 'LI-WSWFr', 'LI-WFrTo']].values.tolist()
    df['aquaculture_water_usage'] = df[['AQ-WGWFr', 'AQ-WGWSa', 'AQ-WGWTo', 'AQ-WSWFr', 'AQ-WSWSa', 'AQ-WSWTo', 'AQ-WFrTo', 'AQ-WSaTo', 'AQ-Wtotl']].values.tolist()
    df['mining_water_usage'] = df[['MI-WGWFr', 'MI-WGWSa', 'MI-WGWTo', 'MI-WSWFr', 'MI-WSWSa', 'MI-WSWTo', 'MI-WFrTo', 'MI-WSaTo', 'MI-Wtotl']].values.tolist()
    df['thermoelectric_power_generation'] = df[['PT-WGWFr', 'PT-WGWSa', 'PT-WGWTo', 'PT-WSWFr', 'PT-WSWSa', 'PT-WSWTo', 'PT-WFrTo', 'PT-WSaTo', 'PT-Wtotl', 'PT-RecWW', 'PT-PSDel', 'PT-CUsFr', 'PT-CUsSa', 'PT-CUTot', 'PT-Power']].values.tolist()
    df['other_thermoelectric_power_generation'] = df[['PO-WGWFr', 'PO-WGWSa', 'PO-WGWTo', 'PO-WSWFr', 'PO-WSWSa', 'PO-WSWTo', 'PO-WFrTo', 'PO-WSaTo', 'PO-Wtotl', 'PO-RecWW', 'PO-PSDel', 'PO-CUsFr', 'PO-CUsSa', 'PO-CUTot', 'PO-Power']].values.tolist()
    df['recirculating_thermoelectric_power_generation'] = df[['PC-WGWFr', 'PC-WGWSa', 'PC-WGWTo', 'PC-WSWFr', 'PC-WSWSa', 'PC-WSWTo', 'PC-WFrTo', 'PC-WSaTo', 'PC-Wtotl', 'PC-RecWW', 'PC-PSDel', 'PC-CUsFr', 'PC-CUsSa', 'PC-CUTot', 'PC-Power']].values.tolist()
    df['total_water_withdrawals'] = df[['TO-WGWFr', 'TO-WGWSa', 'TO-WGWTo', 'TO-WSWFr', 'TO-WSWSa', 'TO-WSWTo', 'TO-WFrTo', 'TO-WSaTo', 'TO-Wtotl', 'TO-CUsFrPartial', 'TO-CUsSaPartial', 'TO-CUTotPartial']].values.tolist()
    
    # Drop original columns
    df.drop(['STATE', 'STATEFIPS', 'COUNTY', 'COUNTYFIPS', 'FIPS', 'YEAR', 'TP-TotPop', 'PS-GWPop', 'PS-SWPop', 'PS-TOPop', 'PS-WGWFr', 'PS-WGWSa',
                 'PS-WGWTo', 'PS-WSWFr', 'PS-WSWSa', 'PS-WSWTo', 'PS-WFrTo', 'PS-WSaTo', 'PS-Wtotl', 'DO-SSPop', 'DO-WGWFr', 'DO-WSWFr', 'DO-WFrTo', 'DO-SSPCp',
                 'DO-PSDel', 'DO-PSPCp', 'DO-WDelv',  'IN-WGWFr', 'IN-WGWSa', 'IN-WGWTo', 'IN-WSWFr', 'IN-WSWSa', 'IN-WSWTo', 'IN-WFrTo', 'IN-WSaTo', 'IN-Wtotl',
                 'IR-WGWFr', 'IR-WSWFr', 'IR-WFrTo', 'IR-RecWW', 'IR-CUsFr', 'IR-IrSpr', 'IR-IrMic', 'IR-IrSur', 'IR-IrTot', 'IC-WGWFr', 'IC-WSWFr', 'IC-WFrTo',
                 'IC-RecWW', 'IC-CUsFr', 'IC-IrSpr', 'IC-IrMic', 'IC-IrSur', 'IC-IrTot', 'IG-WGWFr', 'IG-WSWFr', 'IG-WFrTo', 'IG-RecWW', 'IG-CUsFr', 'IG-IrSpr',
                 'IG-IrMic', 'IG-IrSur', 'IG-IrTot', 'LI-WGWFr', 'LI-WSWFr', 'LI-WFrTo', 'AQ-WGWFr', 'AQ-WGWSa', 'AQ-WGWTo', 'AQ-WSWFr', 'AQ-WSWSa', 'AQ-WSWTo',
                 'AQ-WFrTo', 'AQ-WSaTo', 'AQ-Wtotl', 'MI-WGWFr', 'MI-WGWSa', 'MI-WGWTo', 'MI-WSWFr', 'MI-WSWSa', 'MI-WSWTo', 'MI-WFrTo', 'MI-WSaTo', 'MI-Wtotl', 
                 'PT-WGWFr', 'PT-WGWSa', 'PT-WGWTo', 'PT-WSWFr', 'PT-WSWSa', 'PT-WSWTo', 'PT-WFrTo', 'PT-WSaTo', 'PT-Wtotl', 'PT-RecWW', 'PT-PSDel', 'PT-CUsFr',
                 'PT-CUsSa', 'PT-CUTot', 'PT-Power', 'PO-WGWFr', 'PO-WGWSa', 'PO-WGWTo', 'PO-WSWFr', 'PO-WSWSa', 'PO-WSWTo', 'PO-WFrTo', 'PO-WSaTo', 'PO-Wtotl',
                 'PO-RecWW', 'PO-PSDel', 'PO-CUsFr', 'PO-CUsSa', 'PO-CUTot', 'PO-Power', 'PC-WGWFr', 'PC-WGWSa', 'PC-WGWTo', 'PC-WSWFr', 'PC-WSWSa', 'PC-WSWTo',
                 'PC-WFrTo', 'PC-WSaTo', 'PC-Wtotl', 'PC-RecWW', 'PC-PSDel', 'PC-CUsFr', 'PC-CUsSa', 'PC-CUTot', 'PC-Power', 'TO-WGWFr', 'TO-WGWSa', 'TO-WGWTo',
                 'TO-WSWFr', 'TO-WSWSa', 'TO-WSWTo', 'TO-WFrTo', 'TO-WSaTo', 'TO-Wtotl', 'TO-CUsFrPartial', 'TO-CUsSaPartial', 'TO-CUTotPartial'], axis=1, inplace=True)
    
    # Replace -- with 0s
    df.replace('--', 0, inplace=True)
    
    return df

In [56]:
#df = group_and_drop_columns(df)
#df.head()

,STATE,STATEFIPS,COUNTY,COUNTYFIPS,FIPS,YEAR,TP-TotPop,PS-GWPop,PS-SWPop,PS-TOPop,...,TO-WGWTo,TO-WSWFr,TO-WSWSa,TO-WSWTo,TO-WFrTo,TO-WSaTo,TO-Wtotl,TO-CUsFrPartial,TO-CUsSaPartial,TO-CUTotPartial
1,AL,01,Autauga County,001,01001,2015,55.347,--,--,48.998,...,10.69,45.72,0.00,45.72,56.41,0.00,56.41,13.18,0.00,13.18
2,AL,01,Baldwin County,003,01003,2015,203.709,--,--,174.907,...,73.38,11.32,0.00,11.32,84.70,0.00,84.70,58.28,0.00,58.28
3,AL,01,Barbour County,005,01005,2015,26.489,--,--,24.587,...,6.06,2.96,0.00,2.96,9.02,0.00,9.02,2.96,0.00,2.96
4,AL,01,Bibb County,007,01007,2015,22.583,--,--,20.947,...,5.67,0.20,0.00,0.20,5.87,0.00,5.87,0.19,0.00,0.19
5,AL,01,Blount County,009,01009,2015,57.673,--,--,44.815,...,4.64,55.43,0.00,55.43,60.07,0.00,60.07,1.08,0.00,1.08

# Save Data as CSV File

In [45]:
df.to_csv('clean-data/usco2015v2.0_clean.csv', index=False)